export const AUDIOS_MY_FETCHED = "AUDIOS_MY_FETCHED";

export const AUDIOS_MY_UPDATED = "AUDIOS_MY_UPDATED";

export const AUDIOS_FRIEND_FETCHED = "AUDIOS_FRIEND_FETCHED";

export const AUDIOS_FRIEND_UPDATED = "AUDIOS_FRIEND_UPDATED";

export const AUDIOS_LOADING = "AUDIOS_LOADING";

export const AUDIOS_LOADED = "AUDIOS_LOADED";

export const AUDIOS_ERROR = "AUDIOS_ERROR";

export const AUDIOS_FETCH_COUNT = 50;
