export const GENRES = {
	1:	'Rock',
	2:	'Pop',
	3:	'Rap & Hip-Hop',
	4:	'Easy Listening',
	5:	'Dance & House',
	6:	'Instrumental',
	7:	'Metal',
	8:	'Dubstep',
	10:	'Drum & Bass',
	11:	'Trance',
	12:	'Chanson',
	13:	'Ethnic',
	14:	'Acoustic & Vocal',
	15:	'Reggae',
	16:	'Classical',
	17:	'Indie Pop',
	18:	'Other',
	19:	'Speech',
	21:	'Alternative',
	22:	'Electropop & Disco',
	1001:	'Jazz & Blues'
};
