export const PLAYER_SET_TRACK = "PLAYER_SET_TRACK";

export const PLAYER_SET_PLAYLIST = "PLAYER_SET_PLAYLIST";

export const PLAYER_SET_PLAYLIST_PAGE = "PLAYER_SET_PLAYLIST_PAGE";

export const PLAYER_PLAY_TRACK = "PLAYER_PLAY_TRACK";

export const PLAYER_PLAY_PAUSE = "PLAYER_PLAY_PAUSE";

export const PLAYER_NEXT = "PLAYER_NEXT";

export const PLAYER_PREV = "PLAYER_PREV";
